spring:
  application:
    name: securo-core

  datasource:
    url: jdbc:postgresql://localhost:5432/securo_db
    username: securo_admin
    password: admin

  flyway:
    url: jdbc:postgresql://localhost:5432/securo_db
    user: securo_admin
    password: admin
    table: schema_version

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

securo:
  security:
    jwt:
      secret: 656uzf9s3JhPGu1HSj6nkhV8-Jc-TH43C5Wd5p_BH9Zfbq03n4hWMFlskVP6_tZScNWBOmUAmNxgPVTuOmv6lw
      expiration: 180000
